from tkinter import *
inter = Tk()
inter.geometry("400x500")
inter.title("My Calculator")
inter.config(bg="light grey")
fr = Frame(inter,bg='white',relief=FLAT)
entry = Entry(fr,fg='black',bd=12,justify=RIGHT)
entry.pack(expand=YES,padx=2,pady=2,fil=BOTH)
fr.pack(pady=2,fil=BOTH)
fr1 = Frame(inter,bg='light grey',borderwidth=6)
b1 = Button(fr1,fg='black',bg='grey',text=1,height=3,width=5)
b1.pack(side=LEFT)
b2 = Button(fr1,fg='black',bg='grey',text=2,height=3,width=5)
b2.pack(side=LEFT)
b3 = Button(fr1,fg='black',bg='grey',text=3,height=3,width=5)
b3.pack(side=LEFT)
b4 = Button(fr1,fg='black',bg='grey',text=4,height=3,width=5)
b4.pack(side=LEFT)
fr1.pack(side=LEFT)

fr2 = Frame(inter,bg='light grey',borderwidth=6)
b5 = Button(fr2,fg='black',bg='grey',text=5,height=3,width=5)
b5.pack(side=LEFT)
b6 = Button(fr2,fg='black',bg='grey',text=6,height=3,width=5)
b6.pack(side=LEFT)
b7 = Button(fr2,fg='black',bg='grey',text=7,height=3,width=5)
b7.pack(side=LEFT)
b8 = Button(fr2,fg='black',bg='grey',text=8,height=3,width=5)
b8.pack(side=LEFT)
fr2.pack(side=LEFT)
fr3 = Frame(inter,bg='light grey',borderwidth=6)
b9 = Button(fr2,fg='black',bg='grey',text=9,height=3,width=5)
b9.pack(side=RIGHT)
b0 = Button(fr2,fg='black',bg='grey',text=0,height=3,width=5)
b0.pack(side=RIGHT)

fr3.pack(side=RIGHT)

inter.mainloop()
